apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: timescaledb
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
      # Change for K8s provider:
  # storageClassName: default