version: '2.4'

services:
  worker1:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: go run workers/worker.go
    # command: tail -f /dev/null
    mem_limit: 512MB
    cpus: 1.5
    volumes:
      - ./:/workerdev
      - ./examples:/workerfiles
    environment:
      DP_CODE_FOLDER: ""
      secret_db_host: postgres
      secret_db_user: postgres
      secret_db_pwd: "Hello123!"
      secret_db_ssl: "disable"
      secret_db_port: "5432"
      secret_db_database: "dataplane"
      secret_jwt_secret: "117943e8-9d43-49ac-aa4d-9c64004c8992"
      DP_DATABASE: "timescaledb"
      DP_PORT: "9000"
      DP_NATS: nats://nats:4222
      DP_MODE: "development"
      DP_DEBUG: "true"
      DP_DB_DEBUG: "false"
      DP_MQ_DEBUG: "true"
      DP_METRIC_DEBUG: "false"
      DP_SCHEDULER_DEBUG: "true"
      DP_WORKER_HEARTBEAT_SECONDS: "1"
      DP_WORKER_GROUP: "python_1"
      DP_WORKER_CMD: "/bin/bash"
      DP_WORKER_TYPE: "container"
      DP_WORKER_LB: "roundrobin"
      DP_WORKER_ENV: "Development"
      DP_WORKER_PORT: "9005"

  worker2:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: go run workers/worker.go
    mem_limit: 512MB
    cpus: 1.5
    # command: tail -f /dev/null
    volumes:
      - ./:/workerdev
      - ./examples:/workerfiles
    environment:
      DP_CODE_FOLDER: ""
      secret_db_host: postgres
      secret_db_user: postgres
      secret_db_pwd: "Hello123!"
      secret_db_ssl: "disable"
      secret_db_port: "5432"
      secret_db_database: "dataplane"
      secret_jwt_secret: "117943e8-9d43-49ac-aa4d-9c64004c8992"
      DP_DATABASE: "timescaledb"
      DP_PORT: "9001"
      DP_NATS: nats://nats:4222
      DP_MODE: "development"
      DP_DEBUG: "true"
      DP_DB_DEBUG: "false"
      DP_MQ_DEBUG: "true"
      DP_METRIC_DEBUG: "false"
      DP_SCHEDULER_DEBUG: "true"
      DP_WORKER_HEARTBEAT_SECONDS: "1"
      DP_WORKER_GROUP: "python_1"
      DP_WORKER_CMD: "/bin/bash"
      DP_WORKER_TYPE: "container"
      DP_WORKER_LB: "roundrobin"
      DP_WORKER_ENV: "Development"
      DP_WORKER_PORT: "9005"
  
networks:
  default:
    external: true
    name: dataplane_network
