version: '2.4'

services:
  worker1:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: go run workers/worker.go
    # command: tail -f /dev/null
    mem_limit: 512MB
    # cpu_count: 1
    # cpu_percent: 50
    cpus: 1.5
    volumes:
      - ./:/workerdev
      - ./examples:/workerfiles
    environment:
      env: "local"
      basepath: "/dataplane"
      secret_db_host: postgres
      secret_db_user: postgres
      secret_db_pwd: "Hello123!"
      secret_db_ssl: "disable"
      secret_db_port: "5432"
      secret_db_database: "dataplane"
      secret_jwt_secret: "117943e8-9d43-49ac-aa4d-9c64004c8992"
      database: "timescaledb"
      dataplane_port: "9000"
      dataplane_nats: nats://nats:4222
      mode: "development"
      debug: "true"
      dbdebug: "false"
      messagedebug: "false"
      worker_heartbeat_seconds: "3"
      worker_group: "python_1"
      worker_type: "container"
      worker_lb: "roundrobin"
      worker_env: "Development"
      worker_files: "/workerfiles/"
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '1'
    #       memory: 500M
    #     reservations:
    #       cpus: '0.1'
    #       memory: 100M

  worker2:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: go run workers/worker.go
    mem_limit: 512MB
    cpus: 1.5
    # cpu_percent: 50
    # cpus: 0.5
    # command: tail -f /dev/null
    volumes:
      - ./:/workerdev
      - ./examples:/workerfiles
    environment:
      env: "local"
      basepath: "/dataplane"
      secret_db_host: postgres
      secret_db_user: postgres
      secret_db_pwd: "Hello123!"
      secret_db_ssl: "disable"
      secret_db_port: "5432"
      secret_db_database: "dataplane"
      secret_jwt_secret: "117943e8-9d43-49ac-aa4d-9c64004c8992"
      database: "timescaledb"
      dataplane_port: "9001"
      dataplane_nats: nats://nats:4222
      mode: "development"
      debug: "true"
      dbdebug: "false"
      messagedebug: "false"
      worker_heartbeat_seconds: "3"
      worker_group: "python_2"
      worker_type: "container"
      worker_lb: "roundrobin"
      worker_env: "Development"
      worker_files: "/workerfiles/"

      # Metrics dont pick up resouce limits inside container
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '1'
    #       memory: 500M
    #     reservations:
    #       cpus: '0.1'
    #       memory: 100M
  
networks:
  default:
    external: true
    name: dataplane_network
