name: Cypress-tests

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Build the stack
        run: docker-compose -f cypress-docker-compose.yaml up --build -d

      - run: docker ps
      - run: docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' dataplane_mainapp-cypresstest_1
      - name: Get the ip address of the server
        run: |
          echo "SERVER_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' dataplane_mainapp-cypresstest_1)" >> $GITHUB_ENV

      - name: Server health check
        uses: jtalk/url-health-check-action@v2
        with:
          url: ${{ env.SERVER_IP }}:9001/healthz
          max-attempts: 7
          retry-delay: 5s
      
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          working-directory: ./cypress
          build: yarn
          browser: chrome
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
