name: Cypress-tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Build the stack
        run: docker-compose -f cypress-docker-compose.yaml up --build -d
      
      # - name: Install cypress folder dependencies
      #   run: yarn
      #   working-directory: ./cypress

      - name: Sleep for 30 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '30s'
      
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          working-directory: ./cypress
          build: yarn
          browser: chrome
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
