name: Docker release

on:
  release:
    types: [published]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Tag reference ${{ github.ref }} - version=${{ steps.get_version.outputs.VERSION }}
        run: |
          echo release: ${{ steps.get_version.outputs.VERSION }}
          export dpversion=0.0.${{ steps.get_version.outputs.VERSION }}
          echo docker version: $dpversion

      

          # docker build -t dataplane/dataplane:$dpversion -f docker-build/Dockerfile.main.alpine .
          # docker tag dataplane/dataplane:$dpversion dataplane/dataplane:$dpversion
          # docker push dataplane/dataplane:$dpversion
          # docker tag dataplane/dataplane:$dpversion dataplane/dataplane:latest
          # docker push dataplane/dataplane:latest

          # docker build -t dataplane/dataplane-worker-python:$dpversion -f docker-build/Dockerfile.workerpython.debian .
          # docker tag dataplane/dataplane-worker-python:$dpversion dataplane/dataplane-worker-python:$dpversion
          # docker push dataplane/dataplane-worker-python:$dpversion
          # docker tag dataplane/dataplane-worker-python:$dpversion dataplane/dataplane-worker-python:latest
          # docker push dataplane/dataplane-worker-python:latest